/mnt/ceph/users/abeane/oc_disruption_pt1/run_fixpa_Nov8/analysis
worker1053
Fri Nov  9 05:54:47 EST 2018

Traceback (most recent call last):
  File "gen_movie_acc_map.py", line 12, in <module>
    cluster = dill.load(open(cluster_file, 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: 'cluster_snapshots_actions.p'
Fri Nov  9 05:54:51 EST 2018
